name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Lint with ruff
      run: |
        ruff check src/ --select E,F,W --ignore E501
      continue-on-error: false
    
    - name: Check if main modules import correctly
      run: |
        export PYTHONPATH="${PYTHONPATH}:${PWD}/src"

        python -c "import main; print('✓ main.py imported successfully')"
        python -c "import utils; print('✓ utils.py imported successfully')"
        python -c "import models; print('✓ models.py imported successfully')"

        echo "All modules work fine"
    
    - name: Run main.py (smoke test)
      run: |
        export PYTHONPATH="${PYTHONPATH}:${PWD}/src"

        python src/main.py
      timeout-minutes: 1